baseurl = "http://techaguru.com"
languageCode = "en-us"
title = "TechAguru"
canonifyUrls = "true"

[params]
    description = "Co-creating the future of farming."
    googleAnalytics = "UA-66137010-1"
[[params.social]]
    title = "blog"
    icon = "medium"
    url = "https://blog.techaguru.com"
[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:ask@techaguru.com"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://facebook.com/TechAguru"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/TechAguru"
